//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class database_firewall_rules
    {
        public int id { get; set; }
        public string name { get; set; }
        public string start_ip_address { get; set; }
        public string end_ip_address { get; set; }
        public System.DateTime create_date { get; set; }
        public System.DateTime modify_date { get; set; }
    }
}
namespace Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_MUSICAS
    {
        public int idMusica { get; set; }
        public int idUsuario { get; set; }
        public int idFaixa { get; set; }
        public System.DateTime dtInclusao { get; set; }
    }
}
namespace Models.db
{
    using System;
    using System.Collections.Generic;
    
    public partial class TB_USUARIOS
    {
        public int id { get; set; }
        public string nome { get; set; }
        public string login { get; set; }
        public string senha { get; set; }
    }
}
